# Generated by Django 3.2.20 on 2023-09-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230914_1328'),
        ('users', '0002_auto_20230914_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rel_javed_1_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_javed_1_n', to='home.javed'),
        ),
    ]
